spring:
    jooq:
        sql-dialect: MARIADB_10_7
    jpa:
        show-sql: true
        hibernate:
            ddl-auto : create # hibernate.hbm2ddl.auto 속성에 대한 shortcut이다.
        properties:
            hibernate:
                dialect:
            
    datasource: # Local
        driver-class-name: org.mariadb.jdbc.Driver
        url : jdbc:mariadb://localhost:3306/myboard?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
        username : root
        password : 1234
# Spring Server setup
# server.address=127.0.0.1
# server.port=8080
# server.compression.enabled=true
# server.http2.enabled=true